const Product = require('../schemas/ProductSchema');

const createProduct = async (req, res) => {
    try {
        const { id, name, price, rating, category, description } = req.body;

        // Extract the Cloudinary secure URLs generated by the upload middleware
        const photos = req.files ? req.files.map(file => file.path) : [];

        const newProduct = new Product({
            id: Number(id),
            name,
            price: Number(price),
            rating: Number(rating),
            category,
            description,
            photos
        });

        await newProduct.save();

        res.status(201).json({
            success: true,
            message: 'Product created and saved to MongoDB successfully!',
            product: newProduct
        });

    } catch (error) {
        console.error('Error saving product to MongoDB:', error);
        res.status(500).json({ success: false, error: 'Server error while saving product.' });
    }
};

module.exports = { createProduct };